name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: ./.github/actions/setup-uv

      - name: Install the project
        run: uv sync --locked --group lint

      - name: Run ruff check
        run: |
          uv run --no-sync ruff check

      - name: Run ruff format check
        run: |
          uv run --no-sync ruff format --check

  typechecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: ./.github/actions/setup-uv

      - name: Install the project
        run: uv sync --locked --group typechecker --group test

      - name: Run ty check
        run: |
          uv run --no-sync ty check --output-format github

  test:
    needs: [lint, typechecker]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --group test

      - name: Run pytest
        run: uv run --no-sync pytest
